# Generated by Django 5.2.1 on 2025-06-16 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0002_profile_creci_profile_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('AP', 'Apartamento'), ('CA', 'Casa'), ('CO', 'Cobertura'), ('TE', 'Terreno')], max_length=2)),
                ('localizacao', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quartos', models.PositiveIntegerField()),
                ('banheiros', models.PositiveIntegerField()),
                ('vagas', models.PositiveIntegerField(default=0)),
                ('area', models.DecimalField(decimal_places=2, help_text='Área em m²', max_digits=8)),
                ('condicoes_pagamento', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imoveis/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('corretor', models.ForeignKey(limit_choices_to={'role': 'CORRETOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('total_vendas', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('corretor', models.ForeignKey(limit_choices_to={'role': 'CORRETOR'}, on_delete=django.db.models.deletion.CASCADE, to='contas.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StatusObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FUNDACAO', 'Fundação'), ('ESTRUTURA', 'Estrutura'), ('ACABAMENTO', 'Acabamento'), ('ENTREGUE', 'Entregue')], max_length=20)),
                ('porcentagem', models.PositiveIntegerField(default=0)),
                ('cronograma', models.TextField(help_text='Linha do tempo e previsão de entrega')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_obra', to='corretor.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='Em andamento', max_length=30)),
                ('cliente', models.ForeignKey(limit_choices_to={'role': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='contas.profile')),
                ('corretor', models.ForeignKey(blank=True, limit_choices_to={'role': 'CORRETOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='contas.profile')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretor.imovel')),
            ],
        ),
    ]
