# Generated by Django 5.2.1 on 2025-06-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('EM_OBRA', 'Em obra'), ('ENTREGUE', 'Entregue')], default='DISPONIVEL', max_length=20),
        ),
    ]
