# Generated by Django 5.2.1 on 2025-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0002_imovel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('ESTRUTURACAO', 'Estruturação'), ('ACABAMENTO', 'Acabamento'), ('FINALIZADO', 'Finalizado')], default='ESTRUTURACAO', max_length=20),
        ),
    ]
